export const TopCourse = [
    {
        id: "1",
        category: 'Design',
        name: 'Chloe Angelia',
        imgUrl: '/images/card1.jpg',
        title: 'UI/UX Fundamentals: Your First Lesson',
        tags: ['UI Design', 'Figma'],
        description: 'Learn how to use Figma in this course for beginners',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "2",
        category: 'Design',
        name: 'Jessica Veranda',
        imgUrl: '/images/card2.jpg',
        title: "Ultimate Beginner's Guide to UI/UX Design",
        tags: ['UI Design', 'Adobe XD'],
        description: 'From fundamental concepts to practical tips, this video covers everything you need to know to get started',
        price: 649000,
        discount: 75000,
        rating: 4.5,
    },
    {
        id: "3",
        category: 'Design',
        name: 'Julia Cindy',
        imgUrl: '/images/card3.jpg',
        title: 'Easy UI/UX Design for Absolute Beginners',
        tags: ['UI Design', 'UIX Design'],
        description: 'Enhance your skills and create impressive designs with our expert advice',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "4",
        category: 'Design',
        name: 'Veronica Ashley',
        imgUrl: '/images/card6.jpg',
        title: 'Jumpstart Your UI/UX Design Journey',
        tags: ['Figma', 'Clean Design'],
        description: 'Learn the basics, gain confidence, and begin creating effective and engaging user interfaces',
        price: 499000,
        discount: 799000,
        rating: 4.5,
    },
]

export const TopCourseDev = [
    {
        id: "1",
        category: 'Developer',
        name: 'Julian Christian',
        imgUrl: '/images/cardDev1.jpg',
        title: 'React Native for Beginners',
        tags: ['React Native', 'Mobile Development'],
        description: 'Learn how to use React Native in this course for beginners',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "2",
        category: 'Developer',
        name: 'Franklin Jeremy',
        imgUrl: '/images/cardDev2.jpg',
        title: "Ultimate Beginner's Guide to React",
        tags: ['React', 'Frontend'],
        description: 'From fundamental concepts to practical tips, this video covers everything you need to know to get started',
        price: 649000,
        discount: 75000,
        rating: 4.5,
    },
    {
        id: "3",
        category: 'Developer',
        name: 'Rangga Azof',
        imgUrl: '/images/cardDev3.jpg',
        title: 'Easy React for Absolute Beginners',
        tags: ['React', 'Frontend'],
        description: 'Enhance your skills and create impressive designs with our expert advice',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "4",
        category: 'Developer',
        name: 'Kevin Julio',
        imgUrl: '/images/cardDev4.jpg',
        title: 'Jumpstart Your React Journey',
        tags: ['React', 'Frontend'],
        description: 'Learn the basics, gain confidence, and begin creating effective and engaging user interfaces',
        price: 499000,
        discount: 799000,
        rating: 4.5,
    },
]

export const TopCourseBus = [
    {
        id: "1",
        category: 'Business',
        name: 'Sarah Johnson',
        imgUrl: '/images/cardBus1.jpg',
        title: 'Mastering Business Strategy',
        tags: ['Business Strategy', 'Leadership'],
        description: 'Develop essential strategic thinking skills to drive your business to success',
        price: 899000,
        discount: 1199000,
        rating: 4.7,
    },
    {
        id: "2",
        category: 'Business',
        name: 'Lauren Smith',
        imgUrl: '/images/cardBus2.jpg',
        title: 'Effective Communication in Business',
        tags: ['Communication', 'Leadership'],
        description: 'Improve your communication skills to enhance workplace interactions and productivity',
        price: 599000,
        discount: 799000,
        rating: 4.6,
    },
    {
        id: "3",
        category: 'Business',
        name: 'Emma Brown',
        imgUrl: '/images/cardBus3.jpg',
        title: 'Entrepreneurship Essentials',
        tags: ['Entrepreneurship', 'Startups'],
        description: 'Gain the knowledge and skills needed to start and grow your own business',
        price: 759000,
        discount: 999000,
        rating: 4.8,
    },
    {
        id: "4",
        category: 'Business',
        name: 'Sarah Johnson',
        imgUrl: '/images/cardBus4.jpg',
        title: 'Financial Management for Small Businesses',
        tags: ['Finance', 'Small Business'],
        description: 'Learn how to effectively manage the finances of your small business',
        price: 649000,
        discount: 899000,
        rating: 4.7,
    },
]

export const TopCourseMar = [
    {
        id: "1",
        category: 'Marketing',
        name: 'Olivia Wilson',
        imgUrl: '/images/cardMar1.jpg',
        title: 'Digital Marketing Fundamentals',
        tags: ['Digital Marketing', 'Social Media'],
        description: 'Understand the basics of digital marketing and learn how to implement effective strategies',
        price: 799000,
        discount: 1099000,
        rating: 4.7,
    },
    {
        id: "2",
        category: 'Marketing',
        name: 'Seorina Ladiba',
        imgUrl: '/images/cardMar2.jpg',
        title: 'Social Media Marketing Mastery',
        tags: ['Social Media', 'Content Creation'],
        description: 'Master the art of social media marketing to grow your business and engage with your audience',
        price: 699000,
        discount: 899000,
        rating: 4.8,
    },
    {
        id: "3",
        category: 'Marketing',
        name: 'Sophia Anderson',
        imgUrl: '/images/cardMar3.jpg',
        title: 'Email Marketing for Beginners',
        tags: ['Email Marketing', 'Lead Generation'],
        description: 'Learn how to create effective email marketing campaigns that convert',
        price: 499000,
        discount: 699000,
        rating: 4.6,
    },
    {
        id: "4",
        category: 'Marketing',
        name: 'Emily Quincy',
        imgUrl: '/images/cardMar4.jpg',
        title: 'Content Marketing Strategy',
        tags: ['Content Marketing', 'Branding'],
        description: 'Develop a strong content marketing strategy to build your brand and drive traffic',
        price: 859000,
        discount: 1199000,
        rating: 4.7,
    },
]


