export const TopCourse = [
    {
        id: "1",
        category: 'Design',
        name: 'Chloe Angelia',
        imgUrl: '/images/card1.jpg',
        thumbUrl: '/images/thumb-card-1.jpg',
        thumbUrlMobile: '/images/thumb-card-1.jpg',
        title: 'UI/UX Fundamentals: Your First Lesson',
        tags: ['UI Design', 'Figma'],
        description: 'Learn how to use Figma in this course for beginners',
        fullDesc: [
            "This lesson introduces you to the core principles of UI/UX design, laying a solid foundation for your journey into creating effective digital experiences. You'll explore the key concepts of user interface (UI) design—such as color theory, typography, and layout—alongside the essentials of user experience (UX) design, including user flow, personas, and information architecture.",
            "Through real-world examples, you'll learn the importance of user-centered design and how to align aesthetic choices with usability. This lesson also covers the basics of design tools and techniques to help you start sketching wireframes and low-fidelity prototypes, offering a hands-on introduction to the design process."
        ],
        price: 699000,
        discount: 999000,
        discPercent: '30%',
        rating: 4.5,
        totalRating: 981,
        section: '28',
        lecture: '124',
        duration: '15 hours 05 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'From Zero to Designer: Grasp the Foundations of UI/UX',
    },
    {
        id: "2",
        category: 'Design',
        name: 'Jessica Veranda',
        imgUrl: '/images/card2.jpg',
        thumbUrl: '/images/thumb-card-2.jpg',
        thumbUrlMobile: '/images/thumb-card-2.jpg',
        title: "Ultimate Beginner's Guide to UI/UX Design",
        tags: ['UI Design', 'Adobe XD'],
        description: 'From fundamental concepts to practical tips, this video covers everything you need to know to get started',
        fullDesc: [
            "This guide is designed to help complete beginners take their first steps into the world of UI/UX design, providing a structured path to understand the core concepts and tools used by professionals. You'll begin by exploring the difference between User Interface (UI) and User Experience (UX), understanding how these two fields work together to create seamless digital products.",
            "Through hands-on lessons, you'll learn how to conduct user research, build personas, and develop user flows that align with real-world user needs. From there, you'll dive into the basics of wireframing, prototyping, and usability testing, gaining practical skills to create and iterate on designs. This guide also introduces industry-standard tools such as Figma, Adobe XD, or Sketch, ensuring you are equipped with the knowledge to bring your ideas to life. You'll understand key design principles like visual hierarchy, consistency, and accessibility, and how they contribute to intuitive interfaces."
        ],
        price: 637500,
        discount: 750000,
        discPercent: '15%',
        rating: 4.5,
        totalRating: 2120,
        section: '18',
        lecture: '70',
        duration: '14 hours 48 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'First Steps in UI/UX: Everything Beginners Need to Know',
    },
    {
        id: "3",
        category: 'Design',
        name: 'Julia Cindy',
        imgUrl: '/images/card3.jpg',
        thumbUrl: '/images/thumb-card-3.jpg',
        thumbUrlMobile: '/images/thumb-card-3.jpg',
        title: 'Easy UI/UX Design for Absolute Beginners',
        tags: ['UI Design', 'UIX Design'],
        description: 'Enhance your skills and create impressive designs with our expert advice',
        fullDesc: [
            "This course is tailored for those with no prior experience in design, making UI/UX concepts easy to understand and apply. You'll start by learning the fundamental principles of design thinking and how to create interfaces that are both visually appealing and easy to use.",
            "The lessons focus on practical, step-by-step instructions, guiding you through essential skills like user research, wireframing, prototyping, and usability testing. You'll also explore simple yet powerful design tools such as Figma or Adobe XD, ensuring you can put your new skills into action quickly."
        ],
        price: 699000,
        discount: 999000,
        discPercent: '30%',
        rating: 4.5,
        totalRating: 830,
        section: '32',
        lecture: '111',
        duration: '19 hours 11 minutes',
        language: 'Indonesia',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'Start Your UI/UX Design Journey with Confidence',
    },
    {
        id: "4",
        category: 'Design',
        name: 'Veronica Ashley',
        imgUrl: '/images/card6.jpg',
        thumbUrl: '/images/thumb-card-4.jpg',
        thumbUrlMobile: '/images/thumb-mobile-card-4.jpg',
        title: 'Jumpstart Your UI/UX Design Journey',
        tags: ['Figma', 'Clean Design'],
        description: 'Learn the basics, gain confidence, and begin creating effective and engaging user interfaces',
        fullDesc: [
            "This course offers a comprehensive journey into the field of UI/UX design, equipping you with the knowledge and skills to create user-centered digital experiences. Whether you're new to design or seeking to enhance your existing skills, the course covers every step of the design process—from user research and ideation to wireframing, prototyping, and usability testing. You'll begin by understanding the principles of user experience design, exploring how to conduct user research to identify pain points and needs. From there, you'll learn how to turn ideas into tangible concepts through low-fidelity wireframes and iterate them into fully interactive prototypes. Along the way, the course delves into best practices for information architecture, visual hierarchy, and design systems to ensure consistency and usability across your projects.",
            "The course emphasizes practical, hands-on learning, encouraging you to build designs for real-world applications and iterate based on user feedback. You'll also gain insight into tools and software commonly used in the industry, helping you become proficient in essential design workflows.By the end of the course, you will have a solid grasp of the UI/UX design process—from concept to completion—ready to apply your knowledge to web or mobile platforms. Whether you aspire to become a designer or simply enhance your creativity, this course provides the practical skills and frameworks you need to thrive in the modern design landscape."
        ],
        price: 479000,
        discount: 799000,
        discPercent: '40%',
        rating: 4.5,
        totalRating: 1192,
        section: '16',
        lecture: '92',
        duration: '8 hours 33 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'How to become a professional UI/UX Designer in 2024',
    },
]

export const TopCourseDev = [
    {
        id: "1",
        category: 'Developer',
        name: 'Julian Christian',
        imgUrl: '/images/cardDev1.jpg',
        thumbUrl: '/images/thumb-card-dev-1.jpg',
        thumbUrlMobile: '/images/thumb-card-dev-1.jpg',
        title: 'React Native for Beginners',
        tags: ['React Native', 'Mobile Development'],
        description: 'Learn how to use React Native in this course for beginners',
        fullDesc: [
            "This course introduces you to React Native, the popular framework for building cross-platform mobile applications using JavaScript and React. Designed for those new to mobile development, you'll learn how to create apps that run seamlessly on both iOS and Android from a single codebase.",
            "The course covers the essentials of React Native components, navigation, state management, and API integration, helping you build functional, interactive mobile apps step-by-step. You'll also gain hands-on experience with development tools like Expo and React Native CLI, making it easier to test and deploy your applications."
        ],
        price: 299700,
        discount: 799000,
        discPercent: '70%',
        rating: 4.5,
        totalRating: 1612,
        section: '24',
        lecture: '115',
        duration: '19 hours 29 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'Create Your First App with React Native',
    },
    {
        id: "2",
        category: 'Developer',
        name: 'Franklin Jeremy',
        imgUrl: '/images/cardDev2.jpg',
        thumbUrl: '/images/thumb-card-dev-2.jpg',
        thumbUrlMobile: '/images/thumb-card-dev-2.jpg',
        title: "Ultimate Beginner's Guide to React",
        tags: ['React', 'Frontend'],
        description: 'From fundamental concepts to practical tips, this video covers everything you need to know to get started',
        fullDesc: [
            "This course is designed to help absolute beginners build a solid foundation in React, the popular JavaScript library for building fast, interactive user interfaces. You'll learn the fundamentals of components, props, state, and hooks, which are essential building blocks for any React application.",
            "Through hands-on projects, you'll explore how to create dynamic UIs, manage state efficiently, and handle user interactions. The course also introduces best practices for organizing your code and working with tools like React Developer Tools and create-react-app."
        ],
        price: 720000,
        discount: 799000,
        discPercent: '20%',
        rating: 4.5,
        totalRating: 1992,
        section: '34',
        lecture: '142',
        duration: '18 hours 33 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'Start Your Frontend Journey with React',
    },
    {
        id: "3",
        category: 'Developer',
        name: 'Rangga Azof',
        imgUrl: '/images/cardDev3.jpg',
        thumbUrl: '/images/thumb-card-dev-3.jpg',
        thumbUrlMobile: '/images/thumb-card-dev-3.jpg',
        title: 'Easy React for Absolute Beginners',
        tags: ['React', 'Frontend'],
        description: 'Enhance your skills and create impressive designs with our expert advice',
        fullDesc: [
            "This course makes learning React simple and accessible for those with little to no programming experience. You'll begin with the basics of components, JSX, props, and state, breaking down complex concepts into easy-to-understand lessons. Each topic is accompanied by practical examples to help you see how React works in real-world scenarios.",
            "You'll also explore essential tools like create-react-app to set up your projects, and learn how to create interactive user interfaces with minimal effort. The course introduces React hooks to manage state and side effects, making your components more powerful without unnecessary complexity. By the end of this course, you'll know how to build and structure your own React apps, gaining the confidence to start creating dynamic frontend projects. Whether you aim to build personal projects or are curious about becoming a frontend developer, this course offers a friendly and smooth introduction to React."
        ],
        price: 224000,
        discount: 1120000,
        discPercent: '80%',
        rating: 4.5,
        totalRating: 2419,
        section: '24',
        lecture: '134',
        duration: '21 hours 44 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'Get Started with React Today',
    },
    {
        id: "4",
        category: 'Developer',
        name: 'Kevin Julio',
        imgUrl: '/images/cardDev4.jpg',
        thumbUrl: '/images/thumb-card-dev-4.jpg',
        thumbUrlMobile: '/images/thumb-card-dev-4.jpg',
        title: 'Jumpstart Your React Journey',
        tags: ['React', 'Frontend'],
        description: 'Learn the basics, gain confidence, and begin creating effective and engaging user interfaces',
        fullDesc: [
            "Ready to dive into the world of modern web development? This course is the perfect launchpad for learning React, one of the most popular JavaScript libraries for building user interfaces. You'll start with the basics—understanding components, props, state, and JSX—and gradually move on to creating more dynamic and responsive web apps.",
            "Along the way, you'll learn how to manage data efficiently with hooks and build structured projects with React Router for seamless navigation. This hands-on course ensures that you not only grasp the theoretical concepts but also apply them through practical exercises. You'll explore how to build your first complete React app, gaining essential frontend development skills."
        ],
        price: 559300,
        discount: 799000,
        discPercent: '30%',
        rating: 4.5,
        totalRating: 692,
        section: '12',
        lecture: '92',
        duration: '13 hours 23 minutes',
        language: 'English',
        access: 'Access on mobile and TV',
        certificate: 'Certificate of completion',
        webinar: 'Kickstart Your Web Development with React',
    },
]

export const TopCourseBus = [
    {
        id: "1",
        category: 'Business',
        name: 'Sarah Johnson',
        imgUrl: '/images/cardBus1.jpg',
        title: 'Mastering Business Strategy',
        tags: ['Business Strategy', 'Leadership'],
        description: 'Develop essential strategic thinking skills to drive your business to success',
        price: 899000,
        discount: 1199000,
        rating: 4.7,
    },
    {
        id: "2",
        category: 'Business',
        name: 'Lauren Smith',
        imgUrl: '/images/cardBus2.jpg',
        title: 'Effective Communication in Business',
        tags: ['Communication', 'Leadership'],
        description: 'Improve your communication skills to enhance workplace interactions and productivity',
        price: 599000,
        discount: 799000,
        rating: 4.6,
    },
    {
        id: "3",
        category: 'Business',
        name: 'Emma Brown',
        imgUrl: '/images/cardBus3.jpg',
        title: 'Entrepreneurship Essentials',
        tags: ['Entrepreneurship', 'Startups'],
        description: 'Gain the knowledge and skills needed to start and grow your own business',
        price: 759000,
        discount: 999000,
        rating: 4.8,
    },
    {
        id: "4",
        category: 'Business',
        name: 'Sarah Johnson',
        imgUrl: '/images/cardBus4.jpg',
        title: 'Financial Management for Small Businesses',
        tags: ['Finance', 'Small Business'],
        description: 'Learn how to effectively manage the finances of your small business',
        price: 649000,
        discount: 899000,
        rating: 4.7,
    },
]

export const TopCourseMar = [
    {
        id: "1",
        category: 'Marketing',
        name: 'Olivia Wilson',
        imgUrl: '/images/cardMar1.jpg',
        title: 'Digital Marketing Fundamentals',
        tags: ['Digital Marketing', 'Social Media'],
        description: 'Understand the basics of digital marketing and learn how to implement effective strategies',
        price: 799000,
        discount: 1099000,
        rating: 4.7,
    },
    {
        id: "2",
        category: 'Marketing',
        name: 'Seorina Ladiba',
        imgUrl: '/images/cardMar2.jpg',
        title: 'Social Media Marketing Mastery',
        tags: ['Social Media', 'Content Creation'],
        description: 'Master the art of social media marketing to grow your business and engage with your audience',
        price: 699000,
        discount: 899000,
        rating: 4.8,
    },
    {
        id: "3",
        category: 'Marketing',
        name: 'Sophia Anderson',
        imgUrl: '/images/cardMar3.jpg',
        title: 'Email Marketing for Beginners',
        tags: ['Email Marketing', 'Lead Generation'],
        description: 'Learn how to create effective email marketing campaigns that convert',
        price: 499000,
        discount: 699000,
        rating: 4.6,
    },
    {
        id: "4",
        category: 'Marketing',
        name: 'Emily Quincy',
        imgUrl: '/images/cardMar4.jpg',
        title: 'Content Marketing Strategy',
        tags: ['Content Marketing', 'Branding'],
        description: 'Develop a strong content marketing strategy to build your brand and drive traffic',
        price: 859000,
        discount: 1199000,
        rating: 4.7,
    },
]

export const TrendingCourseItem = [
    {
        id: "1",
        name: "Vera Jean",
        title: "Masterclass in Design Thinking & Creativity",
        imgUrl: "/images/trending-1.jpg",
        tags: ["Design Thinking", "Creativity"],
        desc: "Learn how to use Figma in this course for beginners",
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "2",
        name: "Casandra Lee",
        title: "Business Strategy & Leadership Masterclass",
        imgUrl: "/images/trending-2.jpg",
        tags: ["Business", "Leadership"],
        desc: 'Develop essential strategic thinking skills to drive your business to success',
        price: 699000,
        discount: 999000,
        rating: 4.7,
    },
    {
        id: "3",
        name: "Julia Cindy",
        title: "Digital Marketing & Social Media Mastery",
        imgUrl: "/images/trending-3.jpg",
        tags: ["Marketing", "Social Media"],
        desc: 'Understand the basics of digital marketing and learn how to implement effective strategies',
        price: 699000,
        discount: 999000,
        rating: 4.8,
    },
]

export const trendingCourseThumbnail = [
    {
        id: '09090189sdadas',
        firstName: 'Angelina',
        lastName: 'Lee',
        title: 'Masterclass in Design Thinking, Innovation & Creativity',
        imgUrl: '/images/MainCourse.jpg'
    }
]

export const footerLinksSkill = [
    {
        name: 'Design',
        link: '/',
    },
    {
        name: 'Development',
        link: '/',
    },
    {
        name: 'Business',
        link: '/',
    },
    {
        name: 'Marketing',
        link: '/',
    },
]

export const footerLinksApp = [
    {
        name: 'VSCode',
        link: '/',
    },
    {
        name: 'Figma',
        link: '/',
    },
    {
        name: 'Adobe Photoshop',
        link: '/',
    },
]

export const footerLinksCompany = [
    {
        name: 'Programming',
        link: '/',
    },
    {
        name: 'Photography',
        link: '/',
    },
    {
        name: 'Video Making',
        link: '/',
    },
]
