export const TopCourse = [
    {
        id: "1",
        category: 'Design',
        name: 'Chloe Angelia',
        imgUrl: '/images/card1.jpg',
        title: 'UI/UX Fundamentals: Your First Lesson',
        tags: ['UI Design', 'Figma'],
        description: 'Learn how to use Figma in this course for beginners',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "2",
        category: 'Design',
        name: 'Jessica Veranda',
        imgUrl: '/images/card2.jpg',
        title: "Ultimate Beginner's Guide to UI/UX Design",
        tags: ['UI Design', 'Adobe XD'],
        description: 'From fundamental concepts to practical tips, this video covers everything you need to know to get started',
        price: 649000,
        discount: 75000,
        rating: 4.5,
    },
    {
        id: "3",
        category: 'Design',
        name: 'Julia Cindy',
        imgUrl: '/images/card3.jpg',
        title: 'Easy UI/UX Design for Absolute Beginners',
        tags: ['UI Design', 'UIX Design'],
        description: 'Enhance your skills and create impressive designs with our expert advice',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "4",
        category: 'Design',
        name: 'Veronica Ashley',
        imgUrl: '/images/card6.jpg',
        title: 'Jumpstart Your UI/UX Design Journey',
        tags: ['Figma', 'Clean Design'],
        description: 'Learn the basics, gain confidence, and begin creating effective and engaging user interfaces',
        price: 499000,
        discount: 799000,
        rating: 4.5,
    },
]

export const TopCourseDev = [
    {
        id: "1",
        category: 'Developer',
        name: 'Julian Christian',
        imgUrl: '/images/cardDev1.jpg',
        title: 'React Native for Beginners',
        tags: ['React Native', 'Mobile Development'],
        description: 'Learn how to use React Native in this course for beginners',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "2",
        category: 'Developer',
        name: 'Franklin Jeremy',
        imgUrl: '/images/cardDev2.jpg',
        title: "Ultimate Beginner's Guide to React",
        tags: ['React', 'Frontend'],
        description: 'From fundamental concepts to practical tips, this video covers everything you need to know to get started',
        price: 649000,
        discount: 75000,
        rating: 4.5,
    },
    {
        id: "3",
        category: 'Developer',
        name: 'Rangga Azof',
        imgUrl: '/images/cardDev3.jpg',
        title: 'Easy React for Absolute Beginners',
        tags: ['React', 'Frontend'],
        description: 'Enhance your skills and create impressive designs with our expert advice',
        price: 699000,
        discount: 999000,
        rating: 4.5,
    },
    {
        id: "4",
        category: 'Developer',
        name: 'Kevin Julio',
        imgUrl: '/images/cardDev4.jpg',
        title: 'Jumpstart Your React Journey',
        tags: ['React', 'Frontend'],
        description: 'Learn the basics, gain confidence, and begin creating effective and engaging user interfaces',
        price: 499000,
        discount: 799000,
        rating: 4.5,
    },
]

