import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const DMSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--dm-sans"
}
);

export const metadata: Metadata = {
  title: "Kanabagi Course",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scrollbar-thumb-rounded-full scrollbar-track-rounded-full scrollbar-thin scrollbar-thumb-slate-600 scrollbar-track-slate-800 h-32 overflow-y-scroll">
      <body className={`${DMSans.variable} `}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
